# Generated by Django 5.1 on 2025-02-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='single_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255)),
                ('probe_number', models.CharField(max_length=255)),
                ('a', models.FloatField()),
                ('a1', models.FloatField()),
                ('b', models.FloatField()),
                ('b1', models.FloatField()),
                ('e', models.FloatField()),
                ('d', models.FloatField()),
                ('o1', models.FloatField()),
                ('operator_values', models.TextField()),
                ('shift_values', models.TextField()),
                ('machine_values', models.TextField()),
                ('date_time', models.CharField(max_length=255)),
                ('selected_value', models.CharField(max_length=255)),
                ('selected_mastering', models.CharField(max_length=255)),
            ],
        ),
    ]
