# Generated by Django 5.1 on 2025-02-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_single_master'),
    ]

    operations = [
        migrations.DeleteModel(
            name='single_master',
        ),
        migrations.AlterField(
            model_name='master_settings',
            name='d',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
